name = "BioFetch"
uuid = "f8217676-c24a-4825-a874-ba6ce2a4fe08"
authors = ["Nicholas Bauer <nicholasbauer@outlook.com>"]
version = "0.2.1"

[deps]
BioServices = "a0d4ced5-b29c-5395-b614-ca030a679c4b"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
GenomicAnnotations = "4f8a0a0a-376d-5ac0-ab14-e88793df67f0"

[compat]
BioServices = "0.4"
FASTX = "1, 2"
GenomicAnnotations = "0.2, 0.3"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
